### ISSUE TITLE
这个机器人能接入chatgpt吗？，小白一个，冒昧问下

### ISSUE THREAD

**Issue by fj9876** [gallonyin/worktool#1]

**Comment by gallonyin** [comment]
可以接入chatgpt，需要自己接入QA回调，然后由自己的后台程序对接chatgpt（或其他任意问答库）。文档地址：https://worktool.apifox.cn/doc-861677?nav=2

**Comment by gallonyin** [comment]
现已集成ChatGPT，参见 https://worktool.apifox.cn/api-68569089?nav=2
