### ISSUE TITLE
使用自定义QA消息回调接口，我接口的回答比较慢，机器人不等我返回回答，就退出聊天框了

### ISSUE THREAD

**Issue by GaoZhuoXiu** [gallonyin/worktool#16]
QA消息回调接口我自定义了接收所有单聊和群聊消息，并进行回答处理。然后收到用户的消息后，机器人进入了与用户的对话框，然后我接口回答的比较慢，返回response比较慢，机器人没把消息发出去就退出对话框了，该如何解决

**Comment by qiyulan** [comment]
用群发接口发

**Comment by GaoZhuoXiu** [comment]
我发现文档有介绍：第三方QA接口必须在3秒内处理响应，否则平台将放弃本次请求结果。如果接口确实处理耗时较长，可返回text值为空字符串后异步调用发送消息指令。
目前我已按照这种方式
