### ISSUE TITLE
无法回复群消息

### ISSUE THREAD

**Issue by awewu** [gallonyin/worktool#22]
私聊消息可会回复，群里艾特机器人，机器人会查看消息，但是不会回复。

**Comment by superoidlau** [comment]
检查下回复策略

**Comment by gallonyin** [comment]
1. 回复策略是否设置不回复/不回调
2. 如果回复策略是群聊@机器人时回复，应检查企微昵称和该企微对外显示名是否一致(对外显示名在企微的个人信息页查看修改)，内外名不一致可能导致@识别失效
