### ISSUE TITLE
企业微信内部群中QA消息回调接口接收返回值不匹配

### ISSUE THREAD

**Issue by swallretu** [gallonyin/worktool#29]
在按照QA消息回调接口文档配置和开发好自定义回调接口后，通过在企业微信群内部@机器人来进行回调验证的时候发现，在群里面@机器人回调接口的入参中atMe有时候显示正确，有时候显示不正确。

由于atMe判断不准确所以receivedName和spoken内容也不准确, 以下是我调用过程中的信息截图，群消息和通过worktool api查看历史消息都可以看到消息是@机器人消息，但是回调接口中信息不一致。

环境信息
当前运行host：wss://worktool.asrtts.cn
当前运行版本：2.6.6 Android12 HUAWEI NCO-AL00
企业微信版本：4.1.7

![企业微信截图_81f228db-4a65-4a32-8711-6923bafd412a](https://github.com/gallonyin/worktool/assets/9640815/1ca952f7-c332-413f-80f4-d8c3f3091312)
![1A19E37223DC6079BC1E59EABBB1AAEC](https://github.com/gallonyin/worktool/assets/9640815/b1ac591a-b7f2-4310-a1ee-2ad07781493b)
![D1F22EC9D230BE63D41BC4F7C8460B90](https://github.com/gallonyin/worktool/assets/9640815/7a6274c8-81de-40d9-926a-a0753b106d5a)

**Comment by gallonyin** [comment]
2.6.6可以复现该问题，最新发布2.6.7已修复

**Comment by swallretu** [comment]
感谢回复 @gallonyin
