### ISSUE TITLE
阿里云云手机，原生安卓9。运行报错“环境监测异常，请勿使用本应用”

### ISSUE THREAD

**Issue by zhangzhanhui** [gallonyin/worktool#33]
![image](https://github.com/gallonyin/worktool/assets/4240638/f7ceca68-0c2a-44dc-bba9-533d66c8fc55)

请问哪位大佬知道这个错误该怎么解决？

**Comment by zhangfei8080** [comment]
同求解决方案

**Comment by gallonyin** [comment]
原因是因为该安卓环境系统(ROM)已经开启root权限，并且关闭了SELinux严格模式。
PS：绝大部分APP(当然包括微信、企微)都会认为该系统环境为高风险环境。
