### ISSUE TITLE
发送消息的接口在企业微信群中能否支持引用回复

### ISSUE THREAD

**Issue by winterzhcq** [gallonyin/worktool#37]
目前通过https://worktool.asrtts.cn/wework/sendRawMessage的方式在群里发送消息，只能@人员，无法做到引用回复，引用回复在提供的QA问答接口直接返回可以做到，但是异步调用https://worktool.asrtts.cn/wework/sendRawMessage无法做到引用回复
<img width="1128" alt="image" src="https://github.com/gallonyin/worktool/assets/42427682/25767f62-bbc0-450a-a957-6ac13c9c5ee1">
希望达到如下效果
<img width="526" alt="image" src="https://github.com/gallonyin/worktool/assets/42427682/b1e088ce-f69d-416b-a7be-d0cb19e017c7">

**Comment by gallonyin** [comment]
没有直接提供相关API，可以尝试以下方式：

请求使用通用的发送指令：/wework/sendRawMessage
{
    "socketType":2,
    "list":[
        {
            "type":204,
            "titleList":[
                "待回复目标"
            ],
            "receivedName":"QA消息回调里的值",
            "originalContent":"QA消息回调里的值",
            "receivedContent":"本次回答内容",
            "textType": "QA消息回调里的值"
        }
    ]
}

需要注意，引用回复的内容不在当前机器人可见范围则会引用失败。

**Comment by bianchen1997** [comment]
<img width="566" alt="image" src="https://github.com/gallonyin/worktool/assets/53380900/dc118fcd-6809-463e-89ba-ba2b7d6e2d33">

@gallonyin 按照这个方式使用的情况会是这样,并未达到引用效果,请问是否是我参数问题

> 没有直接提供相关API，可以尝试以下方式：
> 
> 请求使用通用的发送指令：/wework/sendRawMessage { "socketType":2, "list":[ { "type":204, "titleList":[ "待回复目标" ], "receivedName":"QA消息回调里的值", "originalContent":"QA消息回调里的值", "receivedContent":"本次回答内容", "textType": "QA消息回调里的值" } ] }
> 
> 需要注意，引用回复的内容不在当前机器人可见范围则会引用失败。
