### ISSUE TITLE
人脸识别登录实践？

### ISSUE THREAD

**Issue by wang-sy** [gallonyin/worktool#39]
本地手机运行通过，但是遇到一个问题：

![image](https://github.com/gallonyin/worktool/assets/46556407/955dd9c2-dbe5-4bc7-a6fa-c4c2aed3ac3f)

需要人脸识别才能登录，但是云模拟器无法完成，大家有没有相关的实践方法？

**Comment by MinoYexi** [comment]
先用手机登陆后，再使用模拟器试试。

**Comment by gallonyin** [comment]
与worktool无关的问题可在交流群咨询
