### ISSUE TITLE
发送消息推送到错误的群

### ISSUE THREAD

**Issue by MinoYexi** [gallonyin/worktool#43]
使用机器人发送消息推送到错误的群。请问是群名太长导致的吗？

**Comment by dinghangxing** [comment]
匹配下当前房间名称和要进入的群名是否一致

**Comment by MinoYexi** [comment]
> 匹配下当前房间名称和要进入的群名是否一致

看过是一致的，就是群名的前8个字符是一样，后面字符是不一样的。不知道是不是因为这个影响

**Comment by dinghangxing** [comment]
> > 匹配下当前房间名称和要进入的群名是否一致
> 
> 看过是一致的，就是群名的前8个字符是一样，后面字符是不一样的。不知道是不是因为这个影响

我之前的处理是 发送消息进入房间后多加了个名称匹配校验，后面没反馈还有发错群的问题了。可能我们的问题不一样吧

**Comment by MinoYexi** [comment]
> > > 匹配下当前房间名称和要进入的群名是否一致
> > 
> > 
> > 看过是一致的，就是群名的前8个字符是一样，后面字符是不一样的。不知道是不是因为这个影响
> 
> 我之前的处理是 发送消息进入房间后多加了个名称匹配校验，后面没反馈还有发错群的问题了。可能我们的问题不一样吧

大佬是自己改了官方的app吗?

**Comment by gallonyin** [comment]
可更新最新版本，还有错误可上传客户端日志
