### ISSUE TITLE
整个企业微信使用GPT机器人后被封杀了

### ISSUE THREAD

**Issue by LeonLee888** [gallonyin/worktool#6]
还是认证过后的企业微信，放了一个企业微信机器人到微信上，用了四五天吧，突然下线，然后整个企业微信都被封了，投诉了一周还没能解封，该死的微信~

**Comment by gallonyin** [comment]
1. 你是指单个账号被封还是企业被封
2. 企业是否认证
3. 企微生态对GPT回复长文本已经做了风控，必须进行精简和敏感内容处理

**Comment by LeonLee888** [comment]
整个企业被封，还是花过300块认证的企业

**Comment by gallonyin** [comment]
@LeonLee888 

感谢您提供的宝贵信息，我们将脱敏数据做敏感内容审核，没有发现大量异常场景。目前已知是微信和企微会通过文案内容和频繁长文本内容进行风控。
推测原因包括但不限于：
1. 总是以 AI智能模型自称
2. 高频率的长文本回复(疑似刷屏、骚扰)
3. 用户投诉/举报
关于前两点需要您的业务系统对回复内容进行风控拦截、数据截断或分批次处理，但目前而言 WorkTool 仍是最安全可靠的自动化工具。

**Comment by LeonLee888** [comment]
应该是被人举报的~ 确实有点大意，什么人都加

**Comment by gallonyin** [comment]
@LeonLee888 可以提供邮箱，研发会把相关信息发你

**Comment by LeonLee888** [comment]
13217212@qq.com  我看了下，我们是第三级，最严重的处罚，直接封管理员账号的那种，应该是被发现用外挂

**Comment by gallonyin** [comment]
已反馈消息指令列表到指定邮箱。目前未发现与您相同的情况报告

**Comment by LeonLee888** [comment]
收到，我也看到了，应该不是问问题出现的封号~ 可能是被举报用chatgpt，还在申诉中，已经被驳回3次了，看来这企业号是废了
