### ISSUE TITLE
获取群聊不能获取到企业之前的群聊信息。以及同名群聊发送消息只能发送第一个识别的群聊。强烈建议群聊不要用名称匹配。把id做进来

### ISSUE THREAD

**Issue by betterTW** [gallonyin/worktool#9]
获取群聊不能获取到企业之前的群聊信息。以及同名群聊发送消息只能发送第一个识别的群聊。强烈建议群聊不要用名称匹配。把id做进来

**Comment by gallonyin** [comment]
这是三个问题。
1. 获取群聊不能获取到企业之前的群聊信息。如果之前未加入通讯录，我们是看不到群的。
2. 同名群聊发送消息只能发送第一个识别的群聊。这应该是群名称太长导致，建议使用API修改群备注名，自定义备注为为较短的唯一值和群名映射，或等后面增加全群名称回调。
3. 群聊不要用名称匹配，使用id。本项目为非侵入式实现，无法获取id等数据。
